insert into Addresses (uid, area, addressText, postalCode) values (1, 'south', '76400 Monterey Alley', 354970);
insert into Addresses (uid, area, addressText, postalCode) values (2, 'south', '52933 Westport Avenue', 698276);
insert into Addresses (uid, area, addressText, postalCode) values (3, 'west', '645 Montana Court', 568324);
insert into Addresses (uid, area, addressText, postalCode) values (4, 'south', '7937 Barnett Plaza', 277859);
insert into Addresses (uid, area, addressText, postalCode) values (5, 'west', '38554 Grim Lane', 890877);
insert into Addresses (uid, area, addressText, postalCode) values (6, 'north', '28028 5th Drive', 865311);
insert into Addresses (uid, area, addressText, postalCode) values (7, 'south', '84 Knutson Pass', 778392);
insert into Addresses (uid, area, addressText, postalCode) values (8, 'west', '9221 Pine View Road', 305173);
insert into Addresses (uid, area, addressText, postalCode) values (9, 'north', '40730 Sullivan Junction', 933164);
insert into Addresses (uid, area, addressText, postalCode) values (10, 'central', '63334 Hanover Road', 482118);
insert into Addresses (uid, area, addressText, postalCode) values (11, 'north', '15184 John Wall Court', 568443);
insert into Addresses (uid, area, addressText, postalCode) values (12, 'west', '56 Farwell Alley', 250741);
insert into Addresses (uid, area, addressText, postalCode) values (13, 'south', '3 Killdeer Point', 773886);
insert into Addresses (uid, area, addressText, postalCode) values (14, 'south', '16 South Parkway', 853263);
insert into Addresses (uid, area, addressText, postalCode) values (15, 'central', '206 Macpherson Pass', 292747);
insert into Addresses (uid, area, addressText, postalCode) values (16, 'north', '440 Grover Avenue', 124432);
insert into Addresses (uid, area, addressText, postalCode) values (17, 'east', '3891 Walton Park', 114308);
insert into Addresses (uid, area, addressText, postalCode) values (18, 'east', '375 Maple Wood Alley', 258285);
insert into Addresses (uid, area, addressText, postalCode) values (19, 'central', '3769 Delladonna Place', 581332);
insert into Addresses (uid, area, addressText, postalCode) values (20, 'central', '8 Oak Lane', 465360);
insert into Addresses (uid, area, addressText, postalCode) values (21, 'south', '8746 High Crossing Plaza', 606509);
insert into Addresses (uid, area, addressText, postalCode) values (22, 'east', '5 Merry Plaza', 787868);
insert into Addresses (uid, area, addressText, postalCode) values (23, 'south', '02670 Fairfield Drive', 130476);
insert into Addresses (uid, area, addressText, postalCode) values (24, 'south', '032 Lotheville Junction', 439165);
insert into Addresses (uid, area, addressText, postalCode) values (25, 'south', '66 Kedzie Place', 177327);
insert into Addresses (uid, area, addressText, postalCode) values (26, 'east', '145 Gale Point', 156518);
insert into Addresses (uid, area, addressText, postalCode) values (27, 'west', '241 Lawn Plaza', 620058);
insert into Addresses (uid, area, addressText, postalCode) values (28, 'east', '9 Hintze Drive', 242601);
insert into Addresses (uid, area, addressText, postalCode) values (29, 'south', '855 Hallows Plaza', 180766);
insert into Addresses (uid, area, addressText, postalCode) values (30, 'east', '17 Southridge Center', 457282);
insert into Addresses (uid, area, addressText, postalCode) values (31, 'south', '91020 Mifflin Hill', 475101);
insert into Addresses (uid, area, addressText, postalCode) values (32, 'central', '9 Meadow Vale Way', 908378);
insert into Addresses (uid, area, addressText, postalCode) values (33, 'west', '6783 Esker Pass', 398109);
insert into Addresses (uid, area, addressText, postalCode) values (34, 'central', '75886 Reindahl Parkway', 351964);
insert into Addresses (uid, area, addressText, postalCode) values (35, 'north', '1 Macpherson Road', 421309);
