insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (1, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (2, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (3, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (4, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (5, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (6, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (7, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (8, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (9, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (10, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (11, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (12, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (13, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (14, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (15, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (16, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (17, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (18, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (19, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (20, null, null, null, null);
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (21, '2020-05-01 16:19:16.625881+08', '2020-05-01 16:19:16.625881+08', '2020-05-01 16:19:16.625881+08', '2020-05-01 16:19:16.625881+08');
insert into OrderTimes (orderId, timeRiderAssigned, timeRiderArrives, timeRiderDeparted, timeRiderDelivered) values (22, '2020-05-01 16:19:16.625881+08', '2020-05-01 16:19:16.625881+08', '2020-05-01 16:19:16.625881+08', '2020-05-01 16:19:16.625881+08');
