insert into Reviews (orderId, rating, review) values (1, 5, 'bad food');
insert into Reviews (orderId, rating, review) values (2, 1, 'bad service');
insert into Reviews (orderId, rating, review) values (3, 5, 'bad service');
insert into Reviews (orderId, rating, review) values (4, 3, 'got wrong food');
insert into Reviews (orderId, rating, review) values (5, 1, 'great');
insert into Reviews (orderId, rating, review) values (6, 2, 'horrible');
insert into Reviews (orderId, rating, review) values (7, 1, 'good food');
insert into Reviews (orderId, rating, review) values (8, 1, 'good food');
insert into Reviews (orderId, rating, review) values (9, 2, 'good food');
insert into Reviews (orderId, rating, review) values (10, 4, 'good');
insert into Reviews (orderId, rating, review) values (11, 3, 'fast service');
insert into Reviews (orderId, rating, review) values (12, 1, 'great');
insert into Reviews (orderId, rating, review) values (13, 2, 'fast service');
insert into Reviews (orderId, rating, review) values (14, 2, 'prompt');
insert into Reviews (orderId, rating, review) values (15, 4, 'fast service');
insert into Reviews (orderId, rating, review) values (16, 1, 'excellent');
insert into Reviews (orderId, rating, review) values (17, 2, 'good food');
insert into Reviews (orderId, rating, review) values (18, 3, 'bad food');
insert into Reviews (orderId, rating, review) values (19, 2, 'got wrong food');
insert into Reviews (orderId, rating, review) values (20, 1, 'prompt');
