insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (1, 31, 'Temblor Range Clarkia', '$33.22', 11, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (2, 35, 'Dactylospora Lichen', '$2.06', 26, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (3, 28, 'Rusby''s Globemallow', '$22.17', 90, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (4, 31, 'Treefern', '$9.77', 30, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (5, 30, 'Nightblooming Cactus', '$14.78', 13, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (6, 32, 'Lily Of The Incas', '$48.70', 81, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (7, 26, 'Bartramia Moss', '$44.11', 17, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (8, 26, 'Kauai Clermontia', '$34.40', 65, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (9, 33, 'Netleaf Willow', '$47.10', 14, 'korean');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (10, 34, 'Jepson Ceanothus', '$41.52', 19, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (11, 30, 'Rocoto', '$44.77', 45, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (12, 31, 'Downy Lobelia', '$21.99', 11, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (13, 33, 'Flaxleaf Monardella', '$26.92', 24, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (14, 26, 'Schott''s Pygmycedar', '$3.84', 33, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (15, 32, 'Lousewort', '$33.99', 14, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (16, 30, 'Slender Wheatgrass', '$3.75', 66, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (17, 33, 'Rosamond Woollystar', '$45.00', 61, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (18, 32, 'Colicroot', '$34.59', 30, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (19, 29, 'Flameflower', '$47.94', 77, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (20, 26, 'Mesamint', '$33.68', 65, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (21, 26, 'Spider Lupine', '$8.66', 20, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (22, 27, 'Smooth Oxeye', '$5.35', 95, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (23, 32, 'Bush Clockvine', '$49.07', 72, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (24, 28, 'Hulten''s Alkaligrass', '$20.49', 81, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (25, 30, 'Brazilian Bayhops', '$38.99', 86, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (26, 32, 'Roble Beech', '$2.14', 66, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (27, 33, 'Cracked Lichen', '$37.60', 89, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (28, 34, 'Browneyed Susan', '$10.22', 89, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (29, 28, 'Starved Panicgrass', '$10.75', 22, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (30, 28, 'Hairy Fogfruit', '$20.93', 93, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (31, 29, 'Slenderleaf Clammyweed', '$7.94', 49, 'korean');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (32, 33, 'Mexican Sage', '$40.34', 48, 'korean');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (33, 31, 'Andreaea Moss', '$12.39', 21, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (34, 30, 'Prince''s Pine', '$41.71', 91, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (35, 30, 'Woollyleaf Manzanita', '$39.87', 17, 'indian');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (36, 32, 'Beard Lichen', '$27.31', 53, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (37, 26, 'Fendler''s Penstemon', '$40.81', 31, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (38, 26, 'Elegant Hawthorn', '$37.42', 55, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (39, 28, 'Gray Gum', '$32.68', 70, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (40, 29, 'Camden Woollybutt', '$33.42', 12, 'japanese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (41, 33, 'Drummond''s Clematis', '$23.66', 72, 'korean');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (42, 26, 'Fishscale Lichen', '$25.97', 42, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (43, 31, 'Haresfoot Locoweed', '$32.90', 67, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (44, 26, 'Leafy Fiddleleaf', '$19.95', 69, 'korean');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (45, 32, 'Woollyfruit Sedge', '$25.10', 34, 'korean');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (46, 28, 'Desert Bedstraw', '$24.52', 64, 'chinese');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (47, 30, 'Modoc Hawksbeard', '$35.42', 18, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (48, 33, 'Dwarf Crested Iris', '$14.92', 83, 'malay');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (49, 28, 'Fescue', '$25.77', 49, 'western');
insert into Menu (foodId, restaurantId, foodName, price, maxAvailable, category) values (50, 28, 'Ragleaf Bahia', '$34.68', 46, 'western');
